// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ocwip.Api.Data;

#nullable disable

namespace Ocwip.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925150906_AddApplicationAssignments")]
    partial class AddApplicationAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Ocwip.Api.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<JsonElement>("Answers")
                        .HasColumnType("jsonb")
                        .HasColumnName("answers")
                        .HasComment("Answers stored as JSONB, shaped by the form definition this application points at. The contract of this column is settled together with the definition contract in card T-20. Holds personal data, so T-80 has to encrypt the sensitive fields INSIDE the document: ciphertext is neither an object nor an array, so encrypting the whole column would mean dropping both the jsonb type and the check constraint below, and with them the searchability jsonb was chosen for.");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the application is active.");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("FormDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_definition_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number")
                        .HasComment("Application number, assigned at submission and unique within one competition. Null while the application is a draft.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasComment("When the application was submitted, in UTC. Null while it is a draft.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_applications_entity_id");

                    b.HasIndex("CompetitionId", "FormDefinitionId")
                        .HasDatabaseName("ix_applications_competition_id_form_definition_id");

                    b.HasIndex("CompetitionId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_competition_id_number");

                    b.HasIndex("CompetitionId", "Status")
                        .HasDatabaseName("ix_applications_competition_id_status");

                    b.ToTable("applications", null, t =>
                        {
                            t.HasCheckConstraint("ck_applications_answers_is_a_document", "jsonb_typeof(answers) IN ('object', 'array')");

                            t.HasCheckConstraint("ck_applications_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");

                            t.HasCheckConstraint("ck_applications_number_matches_status", "(status = 'Submitted') = (number IS NOT NULL)");

                            t.HasCheckConstraint("ck_applications_submitted_at_matches_status", "(status = 'Submitted') = (submitted_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.ApplicationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the assignment was revoked, in UTC. Null while active.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the assignment revoked. Rows are never removed, because retention is at least 5 years and this row is the proof a reviewer once had access.");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_application_assignments");

                    b.HasIndex("ApplicationId", "ReviewerId")
                        .IsUnique()
                        .HasDatabaseName("ix_application_assignments_application_id_reviewer_id");

                    b.HasIndex("ReviewerId", "IsActive")
                        .HasDatabaseName("ix_application_assignments_reviewer_id_is_active");

                    b.ToTable("application_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_assignments_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.ApplicationStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasComment("When this transition happened, in UTC. Never rewritten: a later transition is a new row, not an update to this one.");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_status");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_application_status_history");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_application_status_history_changed_by_user_id");

                    b.HasIndex("ApplicationId", "ChangedAt")
                        .HasDatabaseName("ix_application_status_history_application_id_changed_at");

                    b.ToTable("application_status_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_status_history_from_ne_to", "from_status <> to_status");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type")
                        .HasComment("MIME type as declared by the client. Declared, not verified: whoever accepts the upload in T-32 owns checking that the bytes match, because a client controlled value proves nothing.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the attachment is active.");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id")
                        .HasComment("Copied from the owning application's entity_id at upload time (T-32), so the authorization handler can answer \"whose is this\" from the attachment row alone.");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("format");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path")
                        .HasComment("Where the stored bytes live. Must not be guessable and must not be reachable without the same permission check as the application itself: an attachment is another organisation's document. Physical storage is card T-32.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_attachments_application_id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_attachments_entity_id");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_storage_path");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachments_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");

                            t.HasCheckConstraint("ck_attachments_size_in_bytes_positive", "size_in_bytes > 0");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the competition is active.");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date")
                        .HasComment("Competition closing date and time stored in UTC, truncated to a whole minute. Submission is rejected at or after this moment. UTC is used to avoid ambiguity caused by local time zones and daylight saving time changes.");

                    b.Property<string>("ExpectedResults")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("expected_results");

                    b.Property<Guid?>("FormDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_definition_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<bool>("IsContinuousIntake")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_continuous_intake")
                        .HasComment("True when the intake never closes on its own, in which case end_date is null.");

                    b.Property<long>("MaxApplicationSizeInBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(52428800L)
                        .HasColumnName("max_application_size_in_bytes");

                    b.Property<long>("MaxAttachmentSizeInBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(10485760L)
                        .HasColumnName("max_attachment_size_in_bytes");

                    b.Property<decimal?>("MaxAverageAnnualRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_average_annual_revenue")
                        .HasComment("Threshold on the average annual revenue of the applicant over the last three closed years. Null means no threshold; zero is a real value.");

                    b.Property<decimal>("MaxGrantAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_grant_amount")
                        .HasComment("Maximum grant amount allowed for the competition. Used later to validate the application budget.");

                    b.Property<decimal?>("MaxIndirectCostPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_indirect_cost_percent");

                    b.Property<decimal?>("MaxInstitutionalDevelopmentPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_institutional_development_percent");

                    b.Property<decimal?>("MinGrantAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_grant_amount");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<string>("PaperSubmissionAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("paper_submission_address");

                    b.Property<DateTimeOffset?>("PaperSubmissionDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paper_submission_deadline")
                        .HasComment("Deadline for the paper copy, in UTC, truncated to a whole minute. Set exactly when requires_paper_submission is true.");

                    b.Property<string>("PercentageBasis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("GrantAmount")
                        .HasColumnName("percentage_basis");

                    b.Property<DateOnly?>("PersonalDataProcessedUntil")
                        .HasColumnType("date")
                        .HasColumnName("personal_data_processed_until")
                        .HasComment("Until when personal data from this competition is processed. Goes into the GDPR clause and may not fall earlier than five years after the intake closes.");

                    b.Property<DateOnly?>("ProjectEndDate")
                        .HasColumnType("date")
                        .HasColumnName("project_end_date");

                    b.Property<DateOnly?>("ProjectStartDate")
                        .HasColumnType("date")
                        .HasColumnName("project_start_date");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at")
                        .HasComment("When an operator published the competition, in UTC. Null while it is still a draft.");

                    b.Property<bool>("RequiresPaperSubmission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_paper_submission")
                        .HasComment("True when a paper copy is required alongside the electronic one. There is no separate paper workflow.");

                    b.Property<string>("RulesUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rules_url");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasComment("Competition start date and time stored in UTC, truncated to a whole minute.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionEmailBody")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("submission_email_body");

                    b.Property<string>("SubmissionNotice")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("submission_notice");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<decimal?>("TotalPoolAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_pool_amount")
                        .HasComment("The pool of the competition, shown to applicants for information. Not a limit checked against anything.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_competitions_number")
                        .HasFilter("is_active");

                    b.HasIndex("Id", "FormDefinitionId")
                        .HasDatabaseName("ix_competitions_id_form_definition_id");

                    b.HasIndex("Status", "EndDate")
                        .HasDatabaseName("ix_competitions_status_end_date");

                    b.ToTable("competitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_competitions_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");

                            t.HasCheckConstraint("ck_competitions_end_date_matches_continuous_intake", "(end_date IS NULL) = is_continuous_intake");

                            t.HasCheckConstraint("ck_competitions_end_date_whole_minute", "date_trunc('minute', end_date AT TIME ZONE 'UTC') = end_date AT TIME ZONE 'UTC'");

                            t.HasCheckConstraint("ck_competitions_max_average_annual_revenue_not_negative", "max_average_annual_revenue >= 0");

                            t.HasCheckConstraint("ck_competitions_max_grant_amount_positive", "max_grant_amount > 0");

                            t.HasCheckConstraint("ck_competitions_min_grant_amount_positive", "min_grant_amount > 0");

                            t.HasCheckConstraint("ck_competitions_min_grant_amount_within_max", "min_grant_amount <= max_grant_amount");

                            t.HasCheckConstraint("ck_competitions_paper_submission_deadline_whole_minute", "date_trunc('minute', paper_submission_deadline AT TIME ZONE 'UTC') = paper_submission_deadline AT TIME ZONE 'UTC'");

                            t.HasCheckConstraint("ck_competitions_paper_submission_fields_match_switch", "requires_paper_submission = (paper_submission_deadline IS NOT NULL) AND requires_paper_submission = (paper_submission_address IS NOT NULL)");

                            t.HasCheckConstraint("ck_competitions_percentages_within_range", "max_indirect_cost_percent BETWEEN 0 AND 100 AND max_institutional_development_percent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_competitions_project_dates_in_order", "project_start_date <= project_end_date");

                            t.HasCheckConstraint("ck_competitions_start_date_before_end_date", "start_date < end_date");

                            t.HasCheckConstraint("ck_competitions_start_date_whole_minute", "date_trunc('minute', start_date AT TIME ZONE 'UTC') = start_date AT TIME ZONE 'UTC'");

                            t.HasCheckConstraint("ck_competitions_total_pool_amount_positive", "total_pool_amount > 0");

                            t.HasCheckConstraint("ck_competitions_upload_limits_positive", "max_attachment_size_in_bytes > 0 AND max_application_size_in_bytes >= max_attachment_size_in_bytes");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.CompetitionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string[]>("AllowedFormats")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_formats");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("requirement");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_competition_attachments");

                    b.HasIndex("CompetitionId", "Position")
                        .HasDatabaseName("ix_competition_attachments_competition_id_position");

                    b.ToTable("competition_attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_competition_attachments_allowed_formats_not_empty", "cardinality(allowed_formats) > 0");

                            t.HasCheckConstraint("ck_competition_attachments_position_not_negative", "position >= 0");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.CompetitionContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_competition_contacts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_competition_contacts_user_id");

                    b.HasIndex("CompetitionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_contacts_competition_id_user_id");

                    b.ToTable("competition_contacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_competition_contacts_position_not_negative", "position >= 0");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.CompetitionCostCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_competition_cost_categories");

                    b.HasIndex("CompetitionId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_cost_categories_competition_id_category");

                    b.ToTable("competition_cost_categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_competition_cost_categories_position_not_negative", "position >= 0");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address")
                        .HasComment("Address. Required for an organisation only, checked at the API edge. Sensitive personal data, encrypted at rest in T-80, which owns checking that 500 still holds the ciphertext.");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contact_information")
                        .HasComment("Contact details of the entity. For an informal group these are a natural person's, so they are sensitive personal data and in scope for encryption at rest in T-80, which owns checking that 500 still holds the ciphertext.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the entity is active.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Nip")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nip")
                        .HasComment("NIP, 10 digits. Required for an organisation only, checked at the API edge and not by the schema. Sensitive data, encrypted at rest in T-80. 10 fits the plaintext number and no ciphertext at all, so T-80 owns widening this column; without that the first encrypted write fails on 22001.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_entities");

                    b.ToTable("entities", null, t =>
                        {
                            t.HasCheckConstraint("ck_entities_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the form definition is active.");

                    b.Property<JsonElement>("Definition")
                        .HasColumnType("jsonb")
                        .HasColumnName("definition")
                        .HasComment("Form structure stored as JSONB. The contract of this column, meaning how sections, fields and validations are shaped, is deliberately not defined here: it is decided in card T-20.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_form_definitions");

                    b.HasAlternateKey("CompetitionId", "Id")
                        .HasName("ak_form_definitions_competition_id_id");

                    b.HasIndex("CompetitionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_form_definitions_competition_id_version_number");

                    b.ToTable("form_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_form_definitions_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");

                            t.HasCheckConstraint("ck_form_definitions_definition_is_a_document", "jsonb_typeof(definition) IN ('object', 'array')");

                            t.HasCheckConstraint("ck_form_definitions_version_number_positive", "version_number > 0");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("concurrency_stamp")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the account is active.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed")
                        .HasComment("Whether the address was confirmed by clicking the link from T-12.2. Replaces the former is_verified column.");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash")
                        .HasComment("Password hash. Never a password, and never written to a log, an error body or an API response.");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("pesel")
                        .HasComment("PESEL. Sensitive personal data, encrypted at rest in T-80. Null until the agreement stage.");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Applicant")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_stamp")
                        .HasDefaultValueSql("gen_random_uuid()::text")
                        .HasComment("Changing this value ends every session of this account. See the session decision in docs/architektura.md.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserName")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entity_id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");

                            t.HasCheckConstraint("ck_users_role_is_known", "role IN ('Applicant', 'Operator', 'Reviewer')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ocwip.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Ocwip.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Ocwip.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Application", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Competition", "Competition")
                        .WithMany("Applications")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_applications_competitions_competition_id");

                    b.HasOne("Ocwip.Api.Models.Entity", "Entity")
                        .WithMany("Applications")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_applications_entities_entity_id");

                    b.HasOne("Ocwip.Api.Models.FormDefinition", "FormDefinition")
                        .WithMany("Applications")
                        .HasForeignKey("CompetitionId", "FormDefinitionId")
                        .HasPrincipalKey("CompetitionId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_applications_form_definitions");

                    b.Navigation("Competition");

                    b.Navigation("Entity");

                    b.Navigation("FormDefinition");
                });

            modelBuilder.Entity("Ocwip.Api.Models.ApplicationAssignment", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Application", "Application")
                        .WithMany("Assignments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_application_assignments_applications_application_id");

                    b.HasOne("Ocwip.Api.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_application_assignments_users_reviewer_id");

                    b.Navigation("Application");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Ocwip.Api.Models.ApplicationStatusHistory", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Application", "Application")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_application_status_history_applications_application_id");

                    b.HasOne("Ocwip.Api.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_application_status_history_users_changed_by_user_id");

                    b.Navigation("Application");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Attachment", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Application", "Application")
                        .WithMany("Attachments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_applications_application_id");

                    b.HasOne("Ocwip.Api.Models.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_entities_entity_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Competition", b =>
                {
                    b.HasOne("Ocwip.Api.Models.FormDefinition", null)
                        .WithMany()
                        .HasForeignKey("Id", "FormDefinitionId")
                        .HasPrincipalKey("CompetitionId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_competitions_form_definitions_id_form_definition_id");
                });

            modelBuilder.Entity("Ocwip.Api.Models.CompetitionAttachment", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Competition", "Competition")
                        .WithMany("Attachments")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_competition_attachments_competitions_competition_id");

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Ocwip.Api.Models.CompetitionContact", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Competition", "Competition")
                        .WithMany("Contacts")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_competition_contacts_competitions_competition_id");

                    b.HasOne("Ocwip.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_competition_contacts_users_user_id");

                    b.Navigation("Competition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ocwip.Api.Models.CompetitionCostCategory", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Competition", "Competition")
                        .WithMany("CostCategories")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_competition_cost_categories_competitions_competition_id");

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Competition", "Competition")
                        .WithMany("FormDefinitions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_form_definitions_competitions_competition_id");

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Ocwip.Api.Models.User", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Entity", "Entity")
                        .WithOne("User")
                        .HasForeignKey("Ocwip.Api.Models.User", "EntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_users_entities_entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Application", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attachments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Competition", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Attachments");

                    b.Navigation("Contacts");

                    b.Navigation("CostCategories");

                    b.Navigation("FormDefinitions");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Entity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
