// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ocwip.Api.Data;

#nullable disable

namespace Ocwip.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827100820_AddDataModels")]
    partial class AddDataModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ocwip.Api.Models.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the competition is active.");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date")
                        .HasComment("Competition closing date and time stored in UTC, truncated to a whole minute. Submission is rejected at or after this moment. UTC is used to avoid ambiguity caused by local time zones and daylight saving time changes.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<decimal>("MaxGrantAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_grant_amount")
                        .HasComment("Maximum grant amount allowed for the competition. Used later to validate the application budget.");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasComment("Competition start date and time stored in UTC, truncated to a whole minute.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("Status", "EndDate")
                        .HasDatabaseName("ix_competitions_status_end_date");

                    b.ToTable("competitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_competitions_end_date_whole_minute", "date_trunc('minute', end_date AT TIME ZONE 'UTC') = end_date AT TIME ZONE 'UTC'");

                            t.HasCheckConstraint("ck_competitions_max_grant_amount_positive", "max_grant_amount > 0");

                            t.HasCheckConstraint("ck_competitions_start_date_before_end_date", "start_date < end_date");

                            t.HasCheckConstraint("ck_competitions_start_date_whole_minute", "date_trunc('minute', start_date AT TIME ZONE 'UTC') = start_date AT TIME ZONE 'UTC'");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the form definition is active.");

                    b.Property<JsonElement>("Definition")
                        .HasColumnType("jsonb")
                        .HasColumnName("definition")
                        .HasComment("Form structure stored as JSONB. The contract of this column, meaning how sections, fields and validations are shaped, is deliberately not defined here: it is decided in card T-20.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_form_definitions");

                    b.HasIndex("CompetitionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_form_definitions_competition_id_version_number");

                    b.ToTable("form_definitions", (string)null);
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Competition", "Competition")
                        .WithMany("FormDefinitions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_form_definitions_competitions_competition_id");

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Competition", b =>
                {
                    b.Navigation("FormDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
