// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ocwip.Api.Data;

#nullable disable

namespace Ocwip.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828121427_AddApplicationAndAccountModels")]
    partial class AddApplicationAndAccountModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ocwip.Api.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<JsonElement>("Answers")
                        .HasColumnType("jsonb")
                        .HasColumnName("answers")
                        .HasComment("Answers stored as JSONB, shaped by the form definition this application points at. The contract of this column is settled together with the definition contract in card T-20. Holds personal data, so T-80 has to encrypt the sensitive fields INSIDE the document: ciphertext is neither an object nor an array, so encrypting the whole column would mean dropping both the jsonb type and the check constraint below, and with them the searchability jsonb was chosen for.");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the application is active.");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("FormDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_definition_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number")
                        .HasComment("Application number, assigned at submission and unique within one competition. Null while the application is a draft.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasComment("When the application was submitted, in UTC. Null while it is a draft.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_applications_entity_id");

                    b.HasIndex("CompetitionId", "FormDefinitionId")
                        .HasDatabaseName("ix_applications_competition_id_form_definition_id");

                    b.HasIndex("CompetitionId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_competition_id_number");

                    b.HasIndex("CompetitionId", "Status")
                        .HasDatabaseName("ix_applications_competition_id_status");

                    b.ToTable("applications", null, t =>
                        {
                            t.HasCheckConstraint("ck_applications_answers_is_a_document", "jsonb_typeof(answers) IN ('object', 'array')");

                            t.HasCheckConstraint("ck_applications_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");

                            t.HasCheckConstraint("ck_applications_number_matches_status", "(status = 'Submitted') = (number IS NOT NULL)");

                            t.HasCheckConstraint("ck_applications_submitted_at_matches_status", "(status = 'Submitted') = (submitted_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type")
                        .HasComment("MIME type as declared by the client. Declared, not verified: whoever accepts the upload in T-32 owns checking that the bytes match, because a client controlled value proves nothing.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the attachment is active.");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path")
                        .HasComment("Where the stored bytes live. Must not be guessable and must not be reachable without the same permission check as the application itself: an attachment is another organisation's document. Physical storage is card T-32.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_attachments_application_id");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_storage_path");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachments_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");

                            t.HasCheckConstraint("ck_attachments_size_in_bytes_positive", "size_in_bytes > 0");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the competition is active.");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date")
                        .HasComment("Competition closing date and time stored in UTC, truncated to a whole minute. Submission is rejected at or after this moment. UTC is used to avoid ambiguity caused by local time zones and daylight saving time changes.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<decimal>("MaxGrantAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_grant_amount")
                        .HasComment("Maximum grant amount allowed for the competition. Used later to validate the application budget.");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasComment("Competition start date and time stored in UTC, truncated to a whole minute.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("Status", "EndDate")
                        .HasDatabaseName("ix_competitions_status_end_date");

                    b.ToTable("competitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_competitions_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");

                            t.HasCheckConstraint("ck_competitions_end_date_whole_minute", "date_trunc('minute', end_date AT TIME ZONE 'UTC') = end_date AT TIME ZONE 'UTC'");

                            t.HasCheckConstraint("ck_competitions_max_grant_amount_positive", "max_grant_amount > 0");

                            t.HasCheckConstraint("ck_competitions_start_date_before_end_date", "start_date < end_date");

                            t.HasCheckConstraint("ck_competitions_start_date_whole_minute", "date_trunc('minute', start_date AT TIME ZONE 'UTC') = start_date AT TIME ZONE 'UTC'");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address")
                        .HasComment("Address. Required for an organisation only, checked at the API edge. Sensitive personal data, encrypted at rest in T-80, which owns checking that 500 still holds the ciphertext.");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contact_information")
                        .HasComment("Contact details of the entity. For an informal group these are a natural person's, so they are sensitive personal data and in scope for encryption at rest in T-80, which owns checking that 500 still holds the ciphertext.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the entity is active.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Nip")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nip")
                        .HasComment("NIP, 10 digits. Required for an organisation only, checked at the API edge and not by the schema. Sensitive data, encrypted at rest in T-80. 10 fits the plaintext number and no ciphertext at all, so T-80 owns widening this column; without that the first encrypted write fails on 22001.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_entities");

                    b.ToTable("entities", null, t =>
                        {
                            t.HasCheckConstraint("ck_entities_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the form definition is active.");

                    b.Property<JsonElement>("Definition")
                        .HasColumnType("jsonb")
                        .HasColumnName("definition")
                        .HasComment("Form structure stored as JSONB. The contract of this column, meaning how sections, fields and validations are shaped, is deliberately not defined here: it is decided in card T-20.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_form_definitions");

                    b.HasAlternateKey("CompetitionId", "Id")
                        .HasName("ak_form_definitions_competition_id_id");

                    b.HasIndex("CompetitionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_form_definitions_competition_id_version_number");

                    b.ToTable("form_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_form_definitions_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");

                            t.HasCheckConstraint("ck_form_definitions_definition_is_a_document", "jsonb_typeof(definition) IN ('object', 'array')");

                            t.HasCheckConstraint("ck_form_definitions_version_number_positive", "version_number > 0");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasComment("When the row was marked inactive, in UTC. Null while the account is active.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("False marks the row as deleted. Rows are never removed, because retention is at least 5 years.");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash")
                        .HasComment("Password hash. Never a password, and never written to a log, an error body or an API response.");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("pesel")
                        .HasComment("PESEL. Sensitive personal data, encrypted at rest in T-80. Null until the agreement stage.");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entity_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_deactivated_at_matches_is_active", "is_active = (deactivated_at IS NULL)");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.Application", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Competition", "Competition")
                        .WithMany("Applications")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_applications_competitions_competition_id");

                    b.HasOne("Ocwip.Api.Models.Entity", "Entity")
                        .WithMany("Applications")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_applications_entities_entity_id");

                    b.HasOne("Ocwip.Api.Models.FormDefinition", "FormDefinition")
                        .WithMany("Applications")
                        .HasForeignKey("CompetitionId", "FormDefinitionId")
                        .HasPrincipalKey("CompetitionId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_applications_form_definitions");

                    b.Navigation("Competition");

                    b.Navigation("Entity");

                    b.Navigation("FormDefinition");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Attachment", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Application", "Application")
                        .WithMany("Attachments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_applications_application_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Competition", "Competition")
                        .WithMany("FormDefinitions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_form_definitions_competitions_competition_id");

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Ocwip.Api.Models.User", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Entity", "Entity")
                        .WithOne("User")
                        .HasForeignKey("Ocwip.Api.Models.User", "EntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_users_entities_entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Application", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Competition", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("FormDefinitions");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Entity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
