// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ocwip.Api.Data;

#nullable disable

namespace Ocwip.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ocwip.Api.Models.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date")
                        .HasComment("Competition closing date and time stored in UTC. Submission is rejected at or after this moment. UTC is used to avoid ambiguity caused by local time zones and daylight saving time changes.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaxGrantAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_grant_amount")
                        .HasComment("Maximum grant amount allowed for the competition. Used later to validate the application budget.");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasComment("Competition start date and time stored in UTC.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.ToTable("competitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_competition_start_date_before_end_date", "start_date < end_date");

                            t.HasCheckConstraint("ck_maxgrantamount_greater_than_0", "max_grant_amount > 0");
                        });
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonElement>("Definition")
                        .HasColumnType("jsonb")
                        .HasColumnName("definition")
                        .HasComment("Form structure stored as JSONB. The JSON contract, including sections, fields and validations, will be defined separately in a future sprint.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_form_definitions");

                    b.HasIndex("CompetitionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_form_definitions_competition_id_version_number");

                    b.ToTable("form_definitions", (string)null);
                });

            modelBuilder.Entity("Ocwip.Api.Models.FormDefinition", b =>
                {
                    b.HasOne("Ocwip.Api.Models.Competition", "Competition")
                        .WithMany("FormDefinitions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_form_definitions_competitions_competition_id");

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Ocwip.Api.Models.Competition", b =>
                {
                    b.Navigation("FormDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
